[package]
name = "dots"
version = "0.9.4"
description = "Dots cross-platform shell"
authors = ["StanleyLl0yd"]
edition = "2021"

[lib]
name = "dots_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = "=2.6.3"

[dependencies]
game-core = { path = "../crates/game-core" }
tauri = "=2.11.3"
tauri-plugin-opener = "=2.5.4"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
debug = 0
incremental = false
